gregkh/usbutils

lsusb.c

Two small fixes for USB 3.x support:
- Correct reporting of MaxPower for USB 3.0 device (#23)
- Proper descriptor type for USB 3.1 hubs

USB 3.x fixes

---

lsusb.c

Very minor UVC Frame descriptor formatting change.
bCopyProtect is a subfield of the frame descriptor, and is not a property of the preceding bit map. Just unindenting it two spaces to accurately reflect this.

Update lsusb.c for UVC 

---

Makefile.am

pkgconfig files should be installed to the arch-dependent library directory, rather than
/usr/share, since they involve arch-dependent files.

Makefile: install pkgconfig file to arch-dependent location

---

lsusb.c

Make the space part of the printf() which uses link_state_descriptions
instead of adding it to each member. Also make the array const char *
const.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

lsusb: Store link state descriptions without preceding space

---

lsusb.c

The BOS descriptor of usb 3.1 devices contain a SuperSpeedPlus capability descriptor that shows 10Gbps speed capabilities.   Display this info.
It's size varies so we can't have a static size for BOS anymore.

Add USB 3.1 SuperSpeedPlus capability descriptor to lsusb -v output

---

lsusb.c

Declare the loop iterator before using it.
Fixes #40
Signed-off-by: Emmanuele Bassi <ebassi@gnome.org>

Don't use C99-ism

---

configure.ac

lsusb needs at least libusb 1.0.9 as it uses libusb_error_name.
Otherwise the build fails with the following linker error:
lsusb-lsusb.o: In function `do_hub':
.../usbutils/lsusb.c:3314: undefined reference to `libusb_error_name'
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

build: Request at least libusb 1.0.9

---

lsusb.c

As I wrote in issue #42, I beleive UUID/GUIDs should be printed with different endianness for the first three fields. There has not been any feedback on this issue, so I am submitting this pull request.

Change endianness of first three fields when printing UUID/GUIDs.

---

autogen.sh

The INSTALL file does not describe how to set up usbhid-dump.
Let's add the git submodule action to autogen.sh.
Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

autogen.sh: checkout usbhid-dump

---

usbreset.c

This is patch adds usability features implemented by Jo-Philipp Wich
and John Crispin for OpenWrt and the LEDE project. It allows the user
to address the device by PID:VID or product name.
Signed-off-by: Bjørn Mork bjorn@mork.no

usbreset.c: import usability improvements from OpenWrt

---

.travis.yml
lsusb.c
travis-autogen.sh

Some more fixes for Travis-CI

---

lsusb.c

Hi, Greg
To display with USB Video Class 1.5 video, add UVC1.5 Video control interface descriptors and do some fix minor bus(line alignment and hexadecimal display value).
Please review it, if you have time :-)
Thanks, jaejoong

add UVC1.5 video control interface descriptors and fix some minor bugs

---

lsusb.c

A set of trivial patches fixing some mistakes when parsing UVC class-specific descriptors.

Fixes for UVC class-specific descriptors in lsusb

---

lsusb.c

The WebUSB specification defines a specific Platform Descriptor in the
Binary Object Store:
https://wicg.github.io/webusb/#webusb-platform-capability-descriptor
Dump the descriptor content and the landing URL it is pointing to.
Tested on a couple of WebUSB devices (probably) implementing the Editor's draft
of the specification.
Signed-off-by: Vincent Palatin <vpalatin@chromium.org>

lsusb: print WebUSB platform descriptor

---

lsusb.c

Add support for dumping UVC Stream Based Format Descriptor according to
section 3.1.1 in "Universal Serial Bus Device Class Definition for Video
Devices: Stream Based Payload", Revision 1.1, June 1, 2005.
Signed-off-by: Torleiv Sundre <torleiv@huddly.com>

lsusb: Dump UVC Stream based payload descriptor.

---

lsusb.py.in

Python2 will become unsupported in next few years, so the tools using it should be ported to python3. And based on this bug https://bugzilla.redhat.com/show_bug.cgi?id=1577010 lsusb is the only package on fedora workstation that is installed by default that requires python2.
Here is my attempt to fix that. But there is a catch. I am a C guy, and I know nothing about python :-) This patch is based on the output of 2to3 tool with a couple of minor tweaks and it works on my machine. So it probably needs a thorough review.

lsusb.py: convert to python3

---

lsusb.py.in

- Use open() and ignore encoding errors
- Replace removed __cmp__ by rich comparison methods
- Convert commented-out print statements, remove unused future import
Fixes #68

lsusb.py: fix up Python 3 conversion

---

usb-devices

This script doesn't use any bashisms, so change the hashbang to /bin/sh.
Fixes #73.
Signed-off-by: Ross Burton <ross.burton@intel.com>

usb-devices: use /bin/sh hashbang

---

lsusb-t.c
lsusb.c
lsusb.h

TL;DR: 
```
$ ./lsusb -t | head -3
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 5000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/3p, 480M
|__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/8p, 480M
$ ./lsusb -tv | head -6    # new!
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 5000M
ID 1d6b:0003 Linux Foundation 3.0 root hub
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/3p, 480M
ID 1d6b:0002 Linux Foundation 2.0 root hub
|__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/8p, 480M
ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
$ ./lsusb -tvv | head -9    # new!
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 5000M
ID 1d6b:0003 Linux Foundation 3.0 root hub
/sys/bus/usb/devices/usb4  /dev/bus/usb/004/001
/:  Bus …
```

lsusb-t: Emit USB IDs and other handy info when verbosity is increased

---

Makefile.am

@gregkh in https://github.com/gregkh/usbutils/issues/34 you voiced concerns about shipping an usbreset.c utility. I saw that in the meantime, usbreset.c was added in https://github.com/gregkh/usbutils/commit/1bfa07c58fdcfb955812f3ce6e28336dd323ff83. My following PR adds build rules for usbreset to Makefile.am, but sets them `noinst_`, so that usbreset doesn't get shipped. I am doing this because builds outside of the automake framework are just cumbersome (especially when headers don't live in standard locations, like it's the case for my distro)
On a personal note: I do understand your concerns about needless support requests, and I would address that by add a warning to usbreset that this is a best effort utility. Not shipping usbreset at all probably causes more "harm" than the harm …

Add usbreset.c as noinst_PROGRAMS target.

---

lsusb.c
names.c
names.h

lsusb tries to get the names for manufacturer and product of a device by
asking the udev hwdb for the names of the device id.
Not every manufacturer and device are in this database. Most devices
however provide those names in the standard USB descriptors, namely
iManufacturer and iProduct.
To get those with libusb we would have to open the device which
requires superuser privileges. To get those values anyway the kernel
provides them in sysfs.
Maybe we want to ask libusb to add the functionality to get those names without having to call `libusb_open`. I couldn't find that functionality.

lsusb: Read unkown names from sysfs device desc.

---

configure.ac

The change to update usbhid-dump in commit 89a279c implicitly changed
the required version of libusb from 1.0.9 to a version that contains
libusb_set_options(). The function was introduced in libusb 1.0.22, so
let's update the pkg-config check to match.
Fixes: #83

Require newer version of libusb

---

configure.ac

This reverts commit 3fe9f89 of usbutils and updates
the usbhid-dump submodule to 209c2b0 which works
around possibly missing libusb_set_option due to a
to old version of libusb.
Since Debian stable (Stretch) contains libusb 1.0.21 (which is one minor version short) the build of usbutils is broken there with no good reason since usbhid-dump is working around it lately. I have
not really tested this with 1.0.9 but with 1.0.21 it builds and runs just fine.

Revert "Require newer version of libusb"

---

Makefile.am
lsusb.8.in

The lsusb binary does not use the usb.ids file anymore, instead it uses
the udev hardware database. Mentionning usb.ids in lsusb(8) is therefore
very confusing for the users. This patch therefore drops that part.

lsusb.8.in: do not mention usb.ids

---

lsusb.c

Fix two minor typos in UVC Extension Unit descriptor to make all the field
names match the UVC 1.1 spec.

lsusb: fix two typos in UVC Extension Unit descriptor

---

usbhid-dump/src/usbhid-dump.c

rindex was removed in POSIX 2008. It is optionally unavailable with
uClibc-ng.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

usbhid-dump: Do not use rindex

---

usb-devices

Several newer USB Device classes are not presently reported individually by
usb-devices, (They are reported as "unk. ").
This patch adds the following classes: 10h (USB Type-C combined Audio/Video
devices) 11h (USB billboard), 12h (USB Type-C Bridge).
As defined at [https://www.usb.org/defined-class-codes]
Signed-off-by: Rob Gill <rrobgill@protonmail.com>

Additional device classes for usb-devices script

---

lsusb.8.in

Commas separating options should not be in bold;
punctuation following variable name should not be in italics.

lsusb(8): fix formatting

---

usbhid-dump/configure.ac

Because usbhid-dump/src/usbhid-dump.c checks for HAVE_LIBUSB_SET_OPTION
It fell out in commit e0525b6
Signed-off-by: Tormod Volden <debian.tormod@gmail.com>

usbhid-dump: Put back autoconf check for libusb_set_option()

---

usbhid-dump/bootstrap

Having `#!/bin/bash` requires that the user has `bash` installed on their system, which may not be the case. There is no reason to require this as the rest of `usbhid-dump/bootstrap` is compatible with `sh`.

bootstrap: change /bin/bash to /bin/sh

---

lsusb.py.in

Do not look for usb.ids in the private paths of other software, as those locations are not public interface.
Signed-off-by: Pino Toscano <toscano.pino@tiscali.it>

lsusb.py: remove private paths for usb.ids

---

Makefile.am
lsusb.c
names.c
names.h
sysfs.c
sysfs.h

First off, I want to acknowledge that this pull request includes a fix for the same issue #108 fixes. I didn't notice that PR until I was almost done with this one, but I do think that the additional code cleanup and refactoring I did makes this PR worth reviewing, even ignoring its other changes.
So what are those other fixes? The commit messages have details, but to summarize they are
1. Ensure that the existing logic to fall back on device-reported vendor/product names from sysfs is consistently applied. Currently, it's not used at all when listing only a single device using `-D`.
2. When running with `-v`, fetch strings for iManufacturer, iProduct, and iSerial from sysfs instead of from libusb. This allows these values to be populated even when we don't have permission to open the …

Fix bug in sysfs path construction and expand usage of sysfs queries

---

lsusb.8.in

Despite the switch to the udev's hardware database being a few years
old, users are still confused when they update usb.ids on their system
and see no effects. This patch therefore updates the lsusb(8) manpage to
mention it.
Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

lsusb(8): mention the udev's hardware database

---

lsusb.c

This PR aims to improve how lsusb displays endpoint addresses in UVC VideoStreaming Interface Descriptors.
For example, lsusb output for my laptop's UVC webcam has changed like this:
```patch
$ diff -u <(lsusb -s 3:6 -vvvvv) <(./lsusb -s 3:6 -vvvvv)
--- /dev/fd/63  2021-01-24 16:27:32.776527685 +0100
+++ /dev/fd/62  2021-01-24 16:27:32.780527727 +0100
@@ -158,7 +158,7 @@
bDescriptorSubtype                  1 (INPUT_HEADER)
bNumFormats                         2
wTotalLength                   0x0233
-        bEndPointAddress                  130
+        bEndpointAddress                 0x82  EP 2 IN
bmInfo                              1
bTerminalLink                       5
bStillCaptureMethod                 1
```

lsusb: Improvements to UVC Interface Descriptor decoding

---

usb-devices

First commit fixes presence detection detection of endpoint-related information, and the others fix formatting of various fields of `I:` and `E:` lines, so that the parsers don't misinterpret them.

Some fixes for printing endpoints and interfaces by usb-devices

---

lsusb.c

When I added these calls, I mistakenly passed them all the size of the `vendor` buffer instead of the buffers they actually fill. As it happens, all the sizes are the same, so there's no correctness issue, but we should still fix the issue for code clarity and ease of modification.

lsusb: Fix buffer size copy/paste error

---

lsusb-t.c

I have a USB device that returns "\n\n" in manufacturer field which
makes newline cleanup in read_sysfs_file_string result in out-of-bound
access.
Fix this by adding lower bound checks in the loops.

lsusb-t: Add lower bound checks in read_sysfs_file_string

---

usb-devices

Fixes:
```console
$ ksh /bin/usb-devices
/bin/usb-devices[92]: local: not found [No such file or directory]
```

usb-devices: do not use `local` in a POSIX shell script

---

lsusb.c

Fixes #126
Signed-off-by: Benson Leung <bleung@chromium.org>

lsusb: Fix typo in string output for iAdditionalInfoURL

---

lsusb.c

Allocation made by `get_dev_string` was not freed.

lsusb.c: fix leak in dump_printer_device

---

desc-defs.c

Found by static analysis:
Expression `(UAC_FORMAT_TYPE_I << 12) + ARRAY_LEN(audio_data_format_type_i)`
evaluates to 6 which is the length of the `audio_data_format_type_i` array.
Therefore, if value is set to 6, the condition evaluates to true and
ouf-of-bound read could occur.

desc-defs.c: fix possible out-of-bound read

---

lsusb.c

Given the requested decriptors are optional, seems like lsusb
should NOT use perror() to communicate why it can't get
the descriptors in question (output is directed to stderr, not stdout).
Further, if we were told to "come back later" (EGAIN),
then it's really not an error.
Only emit this output when user adds "-vv" to the command line.
Signed-off-by: Grant Grundler <grundler@chromium.org>

lsusb: don't complain on EAGAIN

---

names.c

Fix the following error when compiling with undefined sanitizer:
./lsusb
names.c:36:29: runtime error: left shift of 16 by 27 places cannot be represented in type 'int'
Signed-off-by: Han Han <hhan@redhat.com>

Fix an runtime error reported by undefind sanitizer

---

lsusb-t.c

When sorting child devices, only the first child is recursed into. This fix allows all child devices to be recursed into.
Signed-off-by: Tan Li Boon <liboon.tan@mujin.co.jp>

lsusb-t: Fix recursive sorting on child devices.

---

usbreset.c

idProduct at least, is valid as 0, and I guess idVendor can typically be left at 0 while developing some new usb thing.

usbreset: Allow idProduct and idVendor to be 0

---

usb-devices

This change should not make any difference in behavior, but fixes all shellcheck warnings besides https://www.shellcheck.net/wiki/SC3043
Also replacing 'var=`cat file`' with 'read' makes usb-devices much faster.
Old:
real	0m0,849s
user	0m0,388s
sys	0m0,531s
New:
real	0m0,245s
user	0m0,109s
sys	0m0,155s

usb-devices: make shellcheck happy

---

Makefile.am
configure.ac
usbutils.pc.in

Add .pc.in file as proposed in #153.
I'm not really familiar with pkgconfig so someone should maybe have a closer look.
I'm also not sure about the `usb.ids`. `usb.ids` are mentioned in configure.ac but the file seems neither be installed nor generated.
If you want some modifications to this PR just let me know.

Generate usbutils.pc pkgconfig file

---

lsusb.py.in

Please pardon the unsolicited PR, and feel free to ignore it if you don't like it...  
This change adds an option to `lsusb.py` to display the device power/wakeup setting along with other attributes.  It's triggered by option `-w, --wakeup`, so there is no change by default.
I was troubleshooting my own system suspend/resume behavior (still am!) and found it convenient to see this setting along with the other device attributes.

Display (device) power/wakeup via -w option.

---

lsusb.c

On the master branch, device IDs are unsorted. An example from my laptop:
```
Bus 004 Device 003: ID 17ef:a393 Lenovo USB3.1 Hub
Bus 004 Device 004: ID 17ef:a387 Lenovo USB-C Dock Ethernet
Bus 004 Device 002: ID 17ef:a391 Lenovo USB3.1 Hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 0bda:0328 Realtek Semiconductor Corp. USB3.0-CRW
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 008: ID 06cb:009a Synaptics, Inc. Metallica MIS Touch Fingerprint Reader
Bus 001 Device 006: ID 5986:2115 Acer, Inc Integrated Camera
Bus 001 Device 029: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port / Mobile Action MA-8910P
Bus 001 Device 032: ID 045e:0823 Microsoft …
```

lsusb: Add function that sorts the output by device ID.

---

usbutils.pc.in

Both libdir and includedir are defined by autoconf, use these dirs instead of hardcoded dirs.

Honor system libdir and includedir

---

usb-devices

> checkbashisms usb-devices
possible bashism in usb-devices line 78 ('((' should be '$(('):
maxps=$(($(printf "%4i*%s\n" $((maxps_hex & 0x7ff)) \
$((1 + ((maxps_hex >> 11) & 0x3))))))

usb-devices: fix bashism

---

Makefile.am
lsusb.py.1.in

Sam Morris has been kind enough to write a manpage for lsusb.py, based on the lsusb one, and submitted it in the Debian BTS (#1020683). Please find it in this PR with the associated changes to Makefile.am

Add a manpage for lsusb.py

---

Makefile.am

Commit 83690ec408b2 ("Add a manpage for lsusb.py") added the lsusb.py.1 manpage but forgot to add it to DISTCLEANFILES. Fix that.

Add lsusb.py.1 to DISTCLEANFILES

---

lsusb.c

The bcdUSB value 0x0210 defined in USB 3.2 Specification indicates USB 3.2 device operating in one of the USB 2.0 modes. USB 2.0 Link Power Management Addendum defines bcdUSB value 0x0201 to indicate that USB 2.0 device supports the request to read the BOS Descriptor.
The main difference between bcdUSB 0x0210 and 0x0201 is that the USB 3.2 device must support LPM, while USB 2.0 devices can (but are not required to) support LPM.
The difference is respected by USB 3 Gen X Command Verifier (2.3.0.0) Chapter 9 Tests [USB 2 devices], where the test behaves as follows:
* For bcdUSB 0x0200:
Checking Device Under Test for LPM L1 Compatibility...
USB version of device is 2.00.
DUT is NOT compatible with LPM.
LPM is NOT required for DUT
LPM is only supported in USB version 2.01 and above.
* For …

Do not warn about missing LPM bit when not required

---

usbmisc.c

Running lsusb with -D argument and path, which len is more than PATH_MAX + 1, cause stack-buffer-overflow because of copy to the buf a string without null-terminator Force setting 0 byte to the end of the buf fixes this error.

usbmisc: fix possible stack-buffer-overflow

---

lsusb.c

Update the dump_ccid_device function to V1.1 spec (2005) and get rid of the warning about only being accurate for V1.0 for most CCID readers.

Update ccid descriptor dumping to V1.1 spec

---

usb-devices

I recently stumbled over the busybox issue for usb-devices likewise to https://github.com/gregkh/usbutils/pull/181
So here is a new attempted to fix it using the same solution. 
The busybox find command is missing the -printf parameter leading to the error:
find: unrecognized: -printf
Replace the parameter with sed.
This patch was originally created by Daniel Fancsali.

usb-devices: Fix usb-devices with busybox

---

.github/dependabot.yml

Seemingly the CodeQL folks push 1-2 releases a week and the knock on affect is that dependabot will open PRs every week.
Just move to monthly checks/updates.

ci: run monthly checks by dependabot

---

desc-defs.c
lsusb.c
meson.build
sysfs.c
sysfs.h

Nothing particularly hard or controversial here ;-)
As the second patch mentions - perhaps we'd want to fixup/rework the hash tables in `usb-spec.h` ... we should be able to move 1/3 of our text to the (ro)data side. Something for a rainy day.

Resolve "foo discards const qualifier" warnings et al.

---

.github/workflows/codeql.yml
.github/workflows/main.yml
.github/workflows/reuse.yml

Add the identifiers and automate the checking process.

Add the final SPDX identifiers, alongside reuse-lint CI workflow

---

lsusb.c

Add support for parsing the Class-specific VC Interrupt Endpoint Descriptor as described in UVC 1.1 spec 3.8.2.2.
Sample output, including the preceding endpoint descriptor:
```
Endpoint Descriptor:
bLength                 7
bDescriptorType         5
bEndpointAddress     0x81  EP 1 IN
bmAttributes            3
Transfer Type            Interrupt
Synch Type               None
Usage Type               Data
wMaxPacketSize     0x0010  1x 16 bytes
bInterval               8
bMaxBurst               0
VideoControl Endpoint Descriptor:
bLength                 5
bDescriptorType        37
bDescriptorSubtype      3 (EP_INTERRUPT)
wMaxTransferSize       16
```

lsusb: add VideoControl Endpoint Descriptor

---

lsusb.c

Fix the following issues with the usb2 device capability descriptor dump:
Currently, the BESL values claim to be in microseconds, but are actually the raw, unshifted values from the descriptor. Use a lookup table for the BESL values, based on Table X-X1 from "Errata for USB 2.0 ECN: Link Power Management (LPM) - 7/2007" to display the actual microsecond values.
Currently, the BESL values are displayed at the same indentation level as bmAttributes, even though they are fields in bmAttributes. Adjust indentation to align all fields of bmAttributes.
Change "BESL value" to "Baseline BESL value", to reflect the actual names of the field.
Remove two unnecessary line breaks.
Before change:
```
USB 2.0 Extension Device Capability:
bLength                 7
bDescriptorType        16 …
```

lsusb: improve usb2 device capability descriptor

---

.github/actions/setup-debian/action.yml
.github/actions/setup-ubuntu/action.yml
.github/workflows/codeql.yml

Hey Greg, here's a quick PR to silence most of the CodeQL dubious reports. I've also added a couple more CI commits just to keep you on your toes ;-)

ci: codeql ignore meson generated files, et al

---

man/usbreset.1
usbreset.c

**usbreset: support resetting device by serial number**
This is especially useful when multiple devices of the same type (where product id, vendor id, and product name are all matching) are connected to the PC and you want to identify the device uniquely with information which is device-inherent (the bus and device number is not because it will change if the device is connect to a different USB port).
Example call `usbreset`
```
Usage:
usbreset PPPP:VVVV - reset by product and vendor id
usbreset BBB/DDD   - reset by bus and device number
usbreset SN:SERIAL - reset by serial number
usbreset "Product" - reset by product name
Devices:
Number 001/009  ID 0403:6010 Digilent USB Device SN:25163510001
Number 001/006  ID 0403:6011 Digilent USB Device SN:25163520001
Number 001/017  ID 0403:6011 …
```

usbreset: support resetting device by serial number

---

lsusb-t.c

Print an additional line with iManufacturer, iProduct and iSerial strings when available.
Example output from "lsusb -tvvv":
|__ Port 001: Dev 005, If 0, Class=Vendor Specific Class, Driver=[none], 12M
ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
/sys/bus/usb/devices/1-1.1  /dev/bus/usb/001/005
Manufacturer=Prologix Product=Prologix GPIB-USB Controller Serial=PX4IOM5Q

lsusb-t: add verblevel 3 to print_usbdevice()

---

usb-devices

Commit b1c31712134d2b28877b (usb-devices: use 'local' variable type to handle recursion) made several variables local to print_device() to handle recursion. However, devcount was not defined as a local variable. It is currently treated as a global variable causing it to retain values updated across function calls. As a result, USB devices with the same busnum also have the same 'cnt'.
Define devcount as a local variable so 'cnt' is correctly reported for USB devices sharing the same bus and in the same level.

usb-devices: Make devcount 'local' to handle recursion

---

names.c

The switch from hash tables to arrays + linear lookups in #202 (cc @evelikov) created a bug -- `names_genericstrtable` uses two variables (`h` and `t`) inconsistently in a loop, causing it to always return `NULL`, except for the first element in the array table.
This in turn causes everything (except "Usage Page") in the HID descriptors to be `(null)` instead of the right string.
I'm a bit surprised that this hasn't been caught by tests...
For comparison here is a snippet from `lsusb -v` without this patch:
```
Report Descriptor: (length is 103)
Item(Global): Usage Page, data= [ 0x01 ] 1
(null)
Item(Local ): (null), data= [ 0x06 ] 6
(null)
Item(Main  ): (null), data= [ 0x01 ] 1
Application
Item(Global): (null), data= [ 0x01 ] 1
Item(Global): Usage Page, data= [ 0x07 ] 7
(null)
Item(Local …
```

Fix display of HID descriptors
